### ISSUE TITLE
Bazel 1.0.0 incompatibility

### ISSUE THREAD

**Issue by gertvdijk** [cgruber/rules_kotlin#19]
Current HEAD (beab2a80970f0d1e8cea73c74348644491530793) seems to fail with Bazel 1.0.0rc2 (but the very same builds fine with 0.29.1):

```
ERROR: /home/myusername/.cache/bazel/_bazel_myusername/9a5697af4b4898056e1adadcd9c31af8/external/com_github_jetbrains_kotlin/BUILD.bazel:58:5: in kt_jvm_import rule @com_github_jetbrains_kotlin//:kotlin-stdlib-jdk8: 
Traceback (most recent call last):
        File "/home/myusername/.cache/bazel/_bazel_myusername/9a5697af4b4898056e1adadcd9c31af8/external/com_github_jetbrains_kotlin/BUILD.bazel", line 58
                kt_jvm_import(name = 'kotlin-stdlib-jdk8')
        File "/home/myusername/.cache/bazel/_bazel_myusername/9a5697af4b4898056e1adadcd9c31af8/external/io_bazel_rules_kotlin/kotlin/internal/jvm/impl.bzl", line 129, in kt_jvm_import_impl
                struct(kt = kt_info, providers = [Default...])
        File "/home/myusername/.cache/bazel/_bazel_myusername/9a5697af4b4898056e1adadcd9c31af8/external/io_bazel_rules_kotlin/kotlin/internal/jvm/impl.bzl", line 133, in struct
                JavaInfo(output_jar = jars[0], source_jars ... [], <4 more arguments>)
unexpected keywords 'use_ijar', 'source_jars', for call to function JavaInfo(output_jar, compile_jar = None, source_jar = None, neverlink = False, deps = [], runtime_deps = [], exports = [], jdeps = None)
[...]
ERROR: Analysis of target '//<snip>' failed; build aborted: Analysis of target '@com_github_jetbrains_kotlin//:kotlin-stdlib-jdk8' failed; build aborted
INFO: Elapsed time: 3.850s
INFO: 0 processes.
FAILED: Build did NOT complete successfully ([...]
```

I believe this is due to

> Deprecated Java-Starlark API java_common.create_provider is removed. JavaInfo() legacy args (actions, sources, source_jars, use_ijar, java_toolchain, host_javabase) are removed.

as per the [release notes](https://releases.bazel.build/1.0.0/rc2/index.html).

Looks like this is fixed in bazelbuild/rules_kotlin: https://github.com/bazelbuild/rules_kotlin/commit/9051eb053f9c958440603d557316a6e9fda14687, but applying that only doesn't solve it completely; the changes done here in the fork (`kotlin/internal/jvm/impl.bzl`) are similarly incompatible.

**Comment by cgruber** [comment]
Awesome, thanks. It's on my list to get this working with 1.0 this weekend or next week at the latest.

**Comment by cgruber** [comment]
It's gonna be a bit tricky though. I had some issues wiht moving off use_ijar. :/

**Comment by cgruber** [comment]
So, part of this fix got merged from master, but there's a wee bit more to do.  Working on it.

**Comment by cgruber** [comment]
Yeah - some of these were applied in the master branch on the uptream, but the kt_jvm_import never received that love.  THis one should have fixed it.
