### ISSUE TITLE
kotlin build fails with no explanation

### ISSUE THREAD

**Issue by time4tea** [cgruber/rules_kotlin#24]
hi - i'm new to bazel, and trying to build kotlin using this rule set. i'm trying to build a small kotlin library, however I cannot get a successful compile, and nor can I get any information out of the compiler. - The build works fine in gradle, so barring dependency things, it should mostly work.

i get the error:
```
INFO: Analyzed target //backend/common:backend-common (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/richja/dev/backend/common/BUILD:44:1: Compiling Kotlin to JVM //backend/common:backend-common { kt: 117, java: 0, srcjars: 0 } failed (Exit 2)
Target //backend/common:backend-common failed to build
INFO: Elapsed time: 6.457s, Critical Path: 6.37s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

i saw #23 - and have made a local version of the rules that include that fix.

i'm a bit stuck and would really appreciate any guidance in where to look next. 

Thanks!

James

**Comment by cgruber** [comment]
Did that fix work? I've just released a new version, which includes #23.  I'd love to see if that pans out.

**Comment by cgruber** [comment]
Ok, I think I have a lead on this - can you list the third_party deps (e.g. maven deps) you're bringing in?  I have a hunch that some deps used by the kotlin builder are breaking when incompatibile versions are part of the compilation unit. This happened with dagger, but I think I need to be more aggressive with jarjar.  Listing your library's deps would be helpful to validate or falsify this hypothesis. (I'll work up a repro case in any case, but I'm hoping for first-line validation first).

**Comment by time4tea** [comment]
I'm really sorry but I don't have access any longer to the source tree that caused a problem. I'll ask if somebody can try it for me.
James

**Comment by cgruber** [comment]
I got it, fix in place in the main repo.

**Comment by cgruber** [comment]
Fixed in the main repo.
