### ISSUE TITLE
java_binary fails to dep on a kt_jvm_library

### ISSUE THREAD

**Issue by christian-lefty** [cgruber/rules_kotlin#32]
Hello,

I have the following setup:
java_lib A
kt_jvm_library B depends on A and uses kotlin's AutoCloseable feature on a class in A.

java_binary that depends on A and B fails at runtime with the following error:
java.lang.NoClassDefFoundError: kotlin/jdk7/AutoCloseableKt

Is this setup supposed to work?
Do I need to somehow manually pull in some jar that includes those classes?

Thanks

**Comment by cgruber** [comment]
It is, but did you include `org.jetbrains.kotlin:kotlin-stdlib-jdk7` in your deps?  If you're relying on the kt rules to supply the stdlibs during compilation, you might be missing runtime things.

**Comment by christian-lefty** [comment]
Indeed, I added "//3rdparty/jvm/org/jetbrains/kotlin:kotlin_stdlib_jdk7" as a runtime_dep to the binary and it solved it, thanks
