### ISSUE TITLE
Document the proper way of building a deploy jar

### ISSUE THREAD

**Issue by nkoroste** [cgruber/rules_kotlin#33]
Java rules have an option to append `_deploy.jar` to the target name. However, I couldn't find similar solution for the kotlin rules. I tried both `_kt_deploy.jar` and `_deploy.jar`

**Comment by cgruber** [comment]
Neither of these will produce a deploy_jar, which is hte result of a *_binary rule. The kotlin rules make use of the java rules for this.  To deploy a jar you just make a `java_binary(name = "somename_bin", create_executable=False, deps=["//your/library:somename"])` target, and then you can build `//your/library:somename_bin_deploy.jar`
