### ISSUE TITLE
Implicit dependency on kotlin-stdlib-sources.jar

### ISSUE THREAD

**Issue by Kernald** [cgruber/rules_kotlin#34]
I tried to upgrade an Android app from the version 0.29 to 1.0 of those rules. Building the `android_binary` target now fails with this error:
```
ERROR: /Users/kernald/dev/[...]/BUILD:44:12: in deps attribute of android_binary rule //java/[...]: Dependencies on .jar artifacts are not allowed in Android binaries, please use a java_import to depend on external/com_github_jetbrains_kotlin/lib/kotlin-stdlib-sources.jar. If this is an implicit dependency then the rule that introduces it will need to be fixed to account for it correctly.
```
Note that none of the `android_binary` direct dependencies are depending on `kotlin-stdlib`.

**Comment by Kernald** [comment]
Note that this is blocking Bazel 1.0.0 upgrade, as the previous release of those rules is incompatible with Bazel 1.0.0. Should this issue be moved to the upstream repo?

**Comment by cgruber** [comment]
It should, yeah.  Could you re-file it?  Could you also please see if you can fit together a repro?  I'm finding it hard to reproduce. It doesn't happen in our repo, or in my running (for instance) bazel_maven_repository rules examples. It apparently does happen for Jin in rules_jvm_external, but I can't get that to build for some reason. :(

**Comment by cgruber** [comment]
Wait... it's the binary target complaining, meaning it's only showing up because apk generation forbids it. Never mind, I bet I can make a repro.  But please do file it on the main project.

**Comment by cgruber** [comment]
Never mind - someone filed an identical bug bazelbuild/rules_kotlin#208.
