### ISSUE TITLE
kt_jvm_test rule always requires test_class instead of deducing it from the target name

### ISSUE THREAD

**Issue by nkoroste** [cgruber/rules_kotlin#39]
I would expect this `test_class` attribute behave the same as:
https://docs.bazel.build/versions/master/be/java.html#java_test.test_class

Unfortunately, it seems like it's required and not optional in the Kotlin case.

**Comment by cgruber** [comment]
As far as I recall this is fixed in the main repo at bazelbuild/rules_kotlin, and will be available in the next release (probably later this week or early next)

**Comment by nkoroste** [comment]
Thank you!

**Comment by cgruber** [comment]
Fixed in bazelbuild/rules_kotlin#209
